export const wordPairs = [
  // Basic examples
  { correct: 'apple', wrong: 'aple' },
  { correct: 'banana', wrong: 'bananna' },
  { correct: 'cherry', wrong: 'chery' },
  { correct: 'doctor', wrong: 'docter' },
  { correct: 'elephant', wrong: 'elphant' },
  { correct: 'flower', wrong: 'flwer' },
  { correct: 'giraffe', wrong: 'girafe' },
  { correct: 'house', wrong: 'houes' },
  { correct: 'island', wrong: 'iland' },
  { correct: 'jungle', wrong: 'jungel' },

  // Post-UTME must-know tricky spellings
  { correct: 'accommodation', wrong: 'acommodation' },
  { correct: 'maintenance', wrong: 'maintainance' },
  { correct: 'separate', wrong: 'seperate' },
  { correct: 'necessary', wrong: 'neccessary' },
  { correct: 'travelling', wrong: 'traveiling' },
  { correct: 'embarrassment', wrong: 'embarassment' },
  { correct: 'occurrence', wrong: 'occurence' },
  { correct: 'recommend', wrong: 'reccomend' },
  { correct: 'receive', wrong: 'recieve' },
  { correct: 'believe', wrong: 'beleive' },
  { correct: 'privilege', wrong: 'privelege' },
  { correct: 'rhythm', wrong: 'rythm' },
  { correct: 'beautiful', wrong: 'beautifull' },
  { correct: 'success', wrong: 'succes' },
  { correct: 'committee', wrong: 'commitee' },
  { correct: 'broccoli', wrong: 'brocolli' },
  { correct: 'guarantee', wrong: 'garantee' },
  { correct: 'environment', wrong: 'enviroment' },
  { correct: 'government', wrong: 'goverment' },
  { correct: 'argument', wrong: 'arguement' },
  { correct: 'independent', wrong: 'independant' },
  { correct: 'discipline', wrong: 'disipline' },
  { correct: 'humorous', wrong: 'humourous' },
  { correct: 'principal', wrong: 'principle' },
  { correct: 'stationary', wrong: 'stationery' }, // stationery = paper, stationary = not moving
  { correct: 'grateful', wrong: 'greatful' },
  { correct: 'definitely', wrong: 'definately' },
  { correct: 'foreign', wrong: 'forien' },
  { correct: 'height', wrong: 'heigth' },
  { correct: 'weird', wrong: 'wierd' },
  { correct: 'queue', wrong: 'que' },
  { correct: 'knowledge', wrong: 'knoweledge' },
  { correct: 'library', wrong: 'libary' },
  { correct: 'lightning', wrong: 'lightening' },
  { correct: 'possession', wrong: 'possesion' },
  { correct: 'tomorrow', wrong: 'tommorow' },
  { correct: 'temperature', wrong: 'temprature' },
  { correct: 'vehicle', wrong: 'vehicule' },
  { correct: 'restaurant', wrong: 'resturant' },
  { correct: 'acquire', wrong: 'aquire' },
  { correct: 'surprise', wrong: 'suprise' },
  { correct: 'vacuum', wrong: 'vaccum' },
  { correct: 'millennium', wrong: 'millenium' },
  { correct: 'questionnaire', wrong: 'questionaire' },
  { correct: 'entrepreneur', wrong: 'enterpreneur' },
  { correct: 'miscellaneous', wrong: 'miscelaneous' },
  { correct: 'liaison', wrong: 'liason' },
  { correct: 'consensus', wrong: 'concensus' },
  { correct: 'precede', wrong: 'preceed' },
  { correct: 'supersede', wrong: 'supercede' },
  { correct: 'license', wrong: 'lisence' },
  { correct: 'siege', wrong: 'seige' },
  { correct: 'weird', wrong: 'wierd' },
];
